import pandas as pd
import matplotlib.pyplot as plt

# Read the CSV file generated by C
data = pd.read_csv("sorting_results.csv")

# Print data
print(data)

# Plot each sorting algorithm
plt.plot(data["Size"], data["Bubble"], marker="o", label="Bubble Sort")
plt.plot(data["Size"], data["Selection"], marker="o", label="Selection Sort")
plt.plot(data["Size"], data["Insertion"], marker="o", label="Insertion Sort")
plt.plot(data["Size"], data["Merge"], marker="o", label="Merge Sort")
plt.plot(data["Size"], data["Quick"], marker="o", label="Quick Sort")
plt.plot(data["Size"], data["Counting"], marker="o", label="Counting Sort")

# Labels
plt.xlabel("Input Size")
plt.ylabel("Time (seconds)")
plt.title("Sorting Algorithms Time Comparison")

# Show legend
plt.legend()

# Grid
plt.grid(True)

# Display graph
plt.show()
